# Generated by Django 2.2.2 on 2019-08-28 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('grad_year', models.CharField(max_length=255, verbose_name='Graduation Year')),
                ('classes', models.CharField(max_length=255, verbose_name='Class for Partner')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
                ('portfolio_site', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
